# Generated by Django 4.2.3 on 2023-07-29 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_order_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='models',
            options={'ordering': ['price']},
        ),
        migrations.RenameField(
            model_name='models',
            old_name='dercription',
            new_name='description',
        ),
    ]
