# Generated by Django 4.2.3 on 2023-07-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_alter_models_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='models',
            name='archived',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
