# Generated by Django 4.2.3 on 2023-08-15 23:21

from django.db import migrations, models
import shopapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0009_showordersview_order_reciept'),
    ]

    operations = [
        migrations.AddField(
            model_name='models',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=shopapp.models.product_preview_directory_path),
        ),
    ]
