# Generated by Django 4.2.3 on 2023-08-17 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0010_models_preview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShowOrdersView',
        ),
    ]
