# Generated by Django 4.2.3 on 2023-08-25 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0011_delete_showordersview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='models',
            options={'ordering': ['price'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
