# Generated by Django 4.2.3 on 2023-08-17 14:33

from django.db import migrations, models
import myauth.models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0003_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=myauth.models.profile_preview_directory_path),
        ),
    ]
