# Generated by Django 4.2.3 on 2023-08-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0004_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.TextField(null=True),
        ),
    ]
